### ISSUE TITLE
The esversion 6 option in the jshint options is not working

### ISSUE THREAD

**Issue by jamesxv7** [Microsoft/vscode-jshint#18]
Hello, when I try to setup the options of Jshint in the User Settings the editor does not recognize  es version selected.
```
  "jshint.enable": true,
  "jshint.options": {
    "esversion": 6, 
    "esnext": true, 
    "moz": true}
```

**Comment by kieferrm** [comment]
When you run jshint on the command line with the same options you get:
`xyz.js: line 0, col 0, Incompatible values for the 'esversion' and 'esnext' linting options. (0% scanned).`

That problem was fixed with [this commit](https://github.com/Microsoft/vscode-jshint/commit/9747a7df5299ca01e9c577dae7bf71f5b4b8c9b9) several months ago but not yet published to the marked place. I'll do that shortly.

**Comment by str** [comment]
Should esversion be 6 by default?
